[changelog]
header = "# Changelog\n\n"
body = """
{% if version %}
## {{ version }} - {{ timestamp | date(format=\"%Y-%m-%d\") }}
{% else %}
## Unreleased
{% endif %}
{% for group, commits in commits | group_by(attribute=\"group\") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end=\"\") }})
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactoring" },
  { message = "^docs", group = "Documentation" },
  { message = "^build", group = "Build" },
  { message = "^ci", group = "CI" },
  { message = "^test", group = "Tests" },
  { message = "^chore", group = "Misc" },
]
protect_breaking_commits = true
sort_commits = "oldest"
